name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

  scan_ruby:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Scan for security vulnerabilities in JavaScript dependencies
      #   run: bin/importmap audit

  lint:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare the database
        run: bin/rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
